apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-core
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    path: system/base/helm-guestbook
    repoURL: https://github.com/tnpugi/argocd-test.git
    targetRevision: HEAD
    # helm:
    #   releaseName: system-core
    #   valueFiles:
    #   - values.system-core.yaml
---