apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: system-core
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - git:
      repoURL: https://github.com/tnpugi/argocd-test.git
      revision: HEAD
      directories:
      - path: charts/system-core/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/tnpugi/argocd-test.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          values: |
            globals:
              namespace: system-core-{{path.basename}}
              nodePool: system
              project: default
              server: https://kubernetes.default.svc
              environment: base
      destination:
        server: https://kubernetes.default.svc
        namespace: 'system-core-{{path.basename}}'