apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-guestbook
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: helm-guestbook
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: helm-guestbook
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: helm-guestbook
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
