apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.globals.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    scheduler.alpha.kubernetes.io/node-selector: category=system
---