apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.globals.namespacePrefix }}-cert-manager
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: category={{ .Values.globals.nodePool }}
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: {{ .Values.globals.namespacePrefix }}-cert-manager
spec:
  project: {{ .Values.globals.project }}
  destination:
    server: "{{ .Values.globals.server }}"
    namespace: {{ .Values.globals.namespacePrefix }}-cert-manager
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 1.8.1
    helm:
      releaseName: cert-manager
---