apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-core
  namespace: argocd-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: system/base/core
    repoURL: https://github.com/tnpugi/argocd-test
    targetRevision: HEAD
