globals:
  namespacePrefix: system-core
  nodePool: system
  project: default
  server: https://kubernetes.default.svc
  environment: base

# ingress-nginx:
#   installCRDs: true
#   nodeSelector:
#     category: system
#   cainjector:
#     nodeSelector:
#     category: system
#   webhook:
#     nodeSelector:
#       category: system