apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: dummy
  namespace: argocd
spec:
  destination:
    namespace: test
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: charts/system-core/dummy
    repoURL: 'https://github.com/tnpugi/argocd-test.git'
    targetRevision: HEAD
