globals:
  namespace: system-core-cert-manager
  nodePool: system
  project: default
  server: https://kubernetes.default.svc
  environment: base

# cert-manager:
#   installCRDs: true
#   nodeSelector:
#     category: system
#   cainjector:
#     nodeSelector:
#     category: system
#   webhook:
#     nodeSelector:
#       category: system